//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int ComputerID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string ManufacturingDate { get; set; }
        public string Color { get; set; }
        public double Weight { get; set; }
        public double Price { get; set; }
    }
}
